name: Deploy Fullstack App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy ke VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

            cd ~/project/dbs/Front-End-Back-End
            git pull origin main

            echo "Deploying Backend (Hapi.js)..."
            cd backend
            npm install
            npm run build || echo "No build step"
            pm2 restart bloodconnect-api || pm2 start npm --name "bloodconnect-api" -- start

            echo "Deploying Frontend (Vue.js)..."
            cd ../frontend
            npm install
            npm run build

            pm2 delete bloodconnect || true
            pm2 serve dist 3003 --spa --name "bloodconnect"

            pm2 save
