name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy ke VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          script: |
            cd project/dbs/Front-End-Back-End
            git pull origin main
            cd backend
            npm install
            npm run build || echo "No build step"
            pm2 restart bloodconnect-api || pm2 start npm --name "bloodconnect-api" -- start
